version: '3.7'

services:
  bscnode:
    build:
      context: ./src
      dockerfile: Dockerfile_modified
      args:
        NETWORK: ${NETWORK}
        VERSION: ${VERSION}
    container_name: bscnode
    ports:
      - "8545:8545"
      - "8546:8546"
      - "6060:6060"
      - "30311:30311"
      - "30311:30311/udp"
    volumes:
      - ./node:/root/.ethereum
    command: --syncmode ${MODE} --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --verbosity 5
    hostname: bscnode
    image: bscnode-image
    networks:
      - node-access-network
    restart: on-failure

networks:
  node-access-network:
    external: true
