FROM debian:bullseye-slim

RUN apt-get update -y \
  && apt-get install -y curl wget jq unzip \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#1.1.0-beta
ARG VERSION
ARG NETWORK
RUN echo "$VERSION"

COPY geth /geth_linux

RUN wget https://github.com/binance-chain/bsc/releases/download/v${VERSION}/${NETWORK}.zip
RUN unzip ${NETWORK}.zip -d / && \
    sed -i 's/^HTTPHost.*/HTTPHost = "0.0.0.0"/' /config.toml && \
    sed -i '/^WSPort.*/a WSHost = "0.0.0.0"' /config.toml && \
    sed -i 's/^HTTPVirtualHosts.*/HTTPVirtualHosts = ["*"]/' /config.toml && \
    sed -i 's/^HTTPModules.*/HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]/' /config.toml && \
    sed -i 's/^HTTPPort.*/HTTPPort = 8545/' /config.toml && \
    sed -i '/Node\.LogConfig/,/^$/d' /config.toml && \
    sed -i '/^DataDir /d' /config.toml && \
    mv geth_linux /usr/local/bin/bsc && \
    chmod +x /usr/local/bin/bsc

ENV BSC_DATADIR=/root/.ethereum

COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# NODE P2P
EXPOSE 30311/udp
EXPOSE 30311/tcp

# pprof / metrics
EXPOSE 6060/tcp

# HTTP based JSON RPC API
EXPOSE 8545/tcp
# WebSocket based JSON RPC API
EXPOSE 8546/tcp

ENTRYPOINT ["/entrypoint.sh"]

CMD ["bsc"]